#!/bin/bash

# Increase swap size to 6GB (4GB for Gitlab, and 2GB for CI runners)
# SWAP may reduce dramatically the lifespan of your RPi SD Card
# So we highly recommend to move following file on a USB drive
# Size of the swap file, in GiB:
SWAPSIZE=${1:-6}
# Path of the swap file:
SWAPFILE=${2:-/var/swap}
echo "Creating a swap file of ${SWAPSIZE}GiB at ${SWAPFILE} ..."
sudo dphys-swapfile swapoff
free -m
sudo sed -i "s|.*CONF_SWAPSIZE.*|CONF_SWAPSIZE=$((SWAPSIZE*1024))|g" /etc/dphys-swapfile
sudo sed -i "s|.*CONF_SWAPFILE.*|CONF_SWAPFILE=${SWAPFILE}|g" /etc/dphys-swapfile
sudo dd if=/dev/zero | pv -s ${SWAPSIZE}G | sudo dd of=${SWAPFILE} bs=1024 count=$((SWAPSIZE*1024*1024))
sudo chown root:root ${SWAPFILE}
sudo chmod 0600 ${SWAPFILE}
sudo mkswap ${SWAPFILE}
sudo dphys-swapfile swapon
free -m